baseURL = 'https://nervous-feynman-a3a68c.netlify.app'
languageCode = 'en-us'
title = 'Dunia Perkodingan'
theme = 'berkoding'
summaryLength = 20
paginate = 2
[params]
    Description = 'Menapaki jejak koder'